name       : file
version    : 5.33
release    : 14
source     :
    - ftp://ftp.astron.com/pub/file/file-5.33.tar.gz : 1c52c8c3d271cd898d5511c36a68059cda94036111ab293f01f83c3525b737c6
homepage   : http://www.darwinsys.com/file
license    : BSD-2-Clause
component  : system.base
devel      : yes
summary    : file (file type guesser)
description: |
    file is a command used to guess the "file type" of a file.  It reads the content to determine the data.
setup      : |
    %patch -p0 < $pkgfiles/change-dest-for-mgc-file.patch
    %configure --disable-static \
               --enable-shared
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
