name       : file
version    : '5.36'
release    : 17
source     :
    - git|https://github.com/file/file.git : FILE5_36
homepage   : http://www.darwinsys.com/file
license    : BSD-2-Clause
component  : system.base
devel      : yes
summary    : file (file type guesser)
description: |
    file is a command used to guess the "file type" of a file.  It reads the content to determine the data.
setup      : |
    %patch -p1 < $pkgfiles/change-dest-for-mgc-file.patch
    %reconfigure --disable-static \
                 --enable-shared
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check

    # If these don't pass, ypkg will create very broken packages
    TEST1=`file /usr/lib64/libc-2.29.so | grep "ELF 64-bit LSB shared object" | wc -l`
    TEST2=`file /usr/bin/file | grep "ELF 64-bit LSB executable" | wc -l`
    if [ $TEST1 -eq 0 ]; then
        echo "Failed TEST1"
        failtestungracefully
    fi
    if [ $TEST2 -eq 0 ]; then
        echo "Failed TEST2"
        failtestungracefully
    fi
