name       : file
version    : '5.32'
release    : 13
source     :
    - ftp://ftp.astron.com/pub/file/file-5.32.tar.gz : 8639dc4d1b21e232285cd483604afc4a6ee810710e00e579dbe9591681722b50
homepage   : http://www.darwinsys.com/file
license    : BSD-2-Clause
summary    : file (file type guesser)
component  : system.base
devel      : yes
description: |
    file is a command used to guess the "file type" of a file.  It reads the content to determine the data.
setup      : |
    %patch -p0 < $pkgfiles/change-dest-for-mgc-file.patch
    %configure --disable-static \
               --enable-shared
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
